### ISSUE TITLE
按照说明布置好了但是不会抓包了这个程序

### ISSUE THREAD

**Issue by beibeimao** [longhuan1999/sheep#2]
然后 sheep的第83行那个 is topic 写错了is_topic

**Comment by beibeimao** [comment]
然后现在每次进地图他只能输出 =======================

**Comment by beibeimao** [comment]
> 然后 sheep的第83行那个 is topic 写错了is_topic

这个bug是我发现的，bugmacker888 帮忙修改的，我不会修改，我看他报错，然后不知道怎么找到你

**Comment by longhuan1999** [comment]
istopic是我漏了个下划线。我今天才知道怎么开启forked项目的Issues功能。至于抓包对于没接触过的人来说的确不太友好。

**Comment by anymine94** [comment]
> 使用[sheep_manual.py](https://github.com/longhuan1999/sheep/blob/php/sheep_manual.py)
只能用标准模式，直接修改代码里面其它模式会报mitmproxy的错误，是因为我启动方式不对吗。我用的是mitmweb -p 6666 -s sheep.py代码启动，如果不用这个启动，直接点运行，会没有求解那个出来

**Comment by longhuan1999** [comment]
> > 使用[sheep_manual.py](https://github.com/longhuan1999/sheep/blob/php/sheep_manual.py)
> > 只能用标准模式，直接修改代码里面其它模式会报mitmproxy的错误，是因为我启动方式不对吗。我用的是mitmweb -p 6666 -s sheep.py代码启动，如果不用这个启动，直接点运行，会没有求解那个出来

sheep_manual.py已经不是mitm的抓包脚本，只能用python命令执行：python3 sheep_manual.py

**Comment by anymine94** [comment]
python3 autoSolve.py -s reverse

> 
这个命令运行会到开始求解，然后运行完成，不会弹出来X/块数那个地方，打印的python3 autoSolve.py -s reverse，这三个代码也是，会直接运行完成，就没有了

**Comment by longhuan1999** [comment]
> > 使用[sheep_manual.py](https://github.com/longhuan1999/sheep/blob/php/sheep_manual.py)
> > 只能用标准模式，直接修改代码里面其它模式会报mitmproxy的错误，是因为我启动方式不对吗。我用的是mitmweb -p 6666 -s sheep.py代码启动，如果不用这个启动，直接点运行，会没有求解那个出来

旧的的 sheep_manual.py 没把多线程调用求解的函数改成直接调用，所以求解进程还没结束主进程就结束了。抓包脚本sheep.py必须用多线程调用求解否则会阻塞抓包

**Comment by anymine94** [comment]
> 

哦哦，好的感谢
