### ISSUE TITLE
针对一直跑不出解的关卡通关思路

### ISSUE THREAD

**Issue by Angusvencent** [longhuan1999/sheep#5]
您好，能不能新增一个算法，针对何难求解的关卡。使用正序求解高层优先，求解进度大概超过0.92-0.95，就输出有解，保存并发送操作步骤，剩下的十来步操作可以用三个道具辅助人工完成通关。移出和复活有6个格子，加上本身本身的7个格子和打乱道具，应该可以通关。

**Comment by longhuan1999** [comment]
近期我在准备考试和找工作，所以暂时不会再维护这个项目了。
你可以去[BugMaker888/sheep](https://github.com/BugMaker888/sheep)或者[NB-Dragon/SheepSolver](https://github.com/NB-Dragon/SheepSolver)下提issue，看有没有人有兴趣实现这些思路。

**Comment by Angusvencent** [comment]
经过测试，在autoSolve.py和SheepSolver中分别更改添加如下代码，实现了上述思路，但是实际上要么可以直接跑出结果，要么根本求解不到85%......各位自己再优化吧！
(添加了print求解过程中达到的最高进度的操作步骤的代码）

在autoSolve.py中添加记录进度达到85%以上的求解步骤，并导入到map_data的代码：

    while True:
        process = sheep_solver.jindu()
        if second%2 == 0:
            if thread1.is_alive() is False:
                break
        elif second == 1:
            process1 = 0.5
            almostly = []
        elif second >= 1 and second < timeout:
            if process >= 0.5 and process >= process1 and process<0.85:
                process1 = process
                pick_operations = sheep_solver.picked()
                operations = pick_operations["operations"]
                print("     当前最高进度：{}".format(process1), end="")
            if process >= 0.85 and process >= process1:
                print("有进度达到85%，可手动求解\n")
                process1 = process
                picked_operations = sheep_solver.picked()
                almostly = picked_operations["operations"]
        elif second >= timeout:
            if thread1.is_alive():
                stop_thread(thread1)
                print("\n\033[0;33;40m自动求解超时！当前算法有些力不从心，建议放弃挑战并重新开始！\033[0m\n")
                print("==========================================\n")
                print("当前进度为: {}\n最高进度为：{}\n".format(process,process1), end="")
                if almostly != []:
                    with open("map_data_operations.json", "w", encoding="utf8") as f:
                        f.write(json.dumps(picked_operations, indent=4))
                    with open("html/sheep_map/map_data.js", "w", encoding="utf8") as f:
                        f.write(f"const map_data = {json.dumps(picked_operations, indent=4)};")
                    print("==========================================\n")
                    print("未求解成功，当前关卡自动求解步骤已保存到当前路径下 map_data_operations.json 文件!\n")
                    print("剩余步骤不足15%，可利用道具人工求解\n")
                else:
                    print("\n==========================================")
                    print("未求解成功，求解步骤如下:\n"
                      "{}".format(operations), end="")
                print("\n==========================================")
                exit(0)
        time.sleep(1)
        second += 1
        print("\r\033[0;31;40m%s进度：\033[0m%d/%d"%(threadName, second, timeout),end="")



    

在SheepSolver中添加记录进度和求解步骤的2个函数：

    def jindu(self):
        self.jindus = len(self._pick_list) / self._card_count
        return self.jindus

    def picked(self):
        if self._pick_list != []:
            picked_operations = []
            for i in self._pick_list:
                count = 0
                for data_list in self.map_data["levelData"].values():
                    for data_item in data_list:
                        count += 1
                        if count == i:
                            picked_operations.append(data_item["id"])
                            break
                    if count == i:
                        break
            self.map_data["operations"] = picked_operations
            return self.map_data
